### ISSUE TITLE
New app icon

### ISSUE THREAD

**Issue by Tetoq** [alexgleason/harp-gui#27]
I designed two versions of the Harp app icon.
The round square icon I think is more explicit about what makes the app.
The circle icon is more simple but is more actual in term of style.

So, which one do you prefer? 

![icons-harp](https://cloud.githubusercontent.com/assets/14060684/11166333/8136876e-8af4-11e5-9ab6-5c252738cbcc.jpg)

**Comment by alexgleason** [comment]
@sintaxi @kennethormandy Can either of you weigh in on this?

One thing I have noticed is that the depth in icon 1 should probably be removed. The style for OS X as well as Linux icons is to be more flat than that. I like to use the [elementary OS](http://elementary.io/docs/human-interface-guidelines#contrast) documentation as a guideline because it explains the reasoning behind these choices.

Disregarding that, I don't have a very strong opinion between these two. I'm kind of leaning towards the circle one just because I know it will look better at more sizes. The "tab" in the folder icon starts to disappear as the icon gets smaller.

**Comment by sintaxi** [comment]
These both look great. I lean more towards the circle icon myself.

**Comment by alexgleason** [comment]
Sweet. Plus I think the icon sizing argument is a good enough reason to choose the round one. We'll go with the round one. @tetoq can you update the SVG when you get a chance?

**Comment by Tetoq** [comment]
I commit the new icon. If it works we can close this issue.

**Comment by alexgleason** [comment]
@Tetoq This looks great, thank you!

Just so you know, it's better to make a new branch and submit a pull request instead of having two files temporarily in the repo.

It's because git tracks files based on their filename.
